#!/bin/bash
#
# Print Logger - logs print jobs on a minute by minute basis
#

duetdir=$(dirname "$(readlink -f "$0")")
source $duetdir/functions

confcheck

loud=1
debug=1

log=print.$$
date=$(date +%m-%d-%y-%H:%M:%S)

if [ ! -d "$imgdir" ]; then
	mkdir "$imgdir"
fi

if [ ! -d "$logdir" ]; then
	mkdir "$logdir"
fi

while true
do
	allstats=$(statusparser)

	gstatus=$(echo "$allstats" | egrep 'Printing|Idle|EMPTY')

	if [ "$(echo $gstatus | grep Printing )" ] && [ "$printing" = 0 ]
	then
		printing=1
		print_started=$(date +%m-%d-%y-%H:%M:%S)
		echo "Detected new print at $print_started"
	elif [ "$(echo $gstatus | egrep 'Idle' )" ]
	then
		printing=0
	elif [ "$gstatus" = EMPTY ]
	then
		echo "No data from the printer; polling less freqently. When communication resumes we will treat it as a new print for logging and snapshot purposes."
		printing=0
	fi

	if [ "$printing" = 1 ] # Handle_printing actually does stuff; this is a lightweight script to poll and monitor
	then
		handle_printing $print_started
	fi

	if [ "$printing" = 1 ]
	then
		sleep $print_poll
	else
		sleep $poll
	fi
done

