#!/bin/bash
#
# Print Logger - logs print jobs on a minute by minute basis - just grabs raw status and prints it to stdout. 
#

type=${1:-2}

duetdir=$(dirname "$(readlink -f "$0")")
source $duetdir/functions

confcheck

log=mylog.$$

status=$(curl -s http://$ip/rr_status?type=$type)

echo $status

