#!/usr/bin/python3

import json
import sys
import requests
import datetime
import urllib.parse
import time
import subprocess
import sys

command = sys.argv[0]

target = sys.argv[1]

ip = '192.168.1.88'
baseurl = 'http://' + ip + '/'
output = '/tmp/file'
log = open(output, 'a')

targetdir = os.environ['HOME']


def furld(url):
    response = requests.get(url)


def whut(are_you_ell):
    return duet, status


def get_duet(item):
    duet = get_state()[0]
    return duet[item]


def call(file, destination):
    if destination = duet:
        return


def ls(arg):
    return


def bad_ui(command):
    if command = ls:
        ls(arg)
    if command = get:
        get(arg)
    if command = put:
        put(arg)
    else:
        exit

 def input():
     file = raw_input("
